#!/usr/bin/env bash
#
# This script checks out the branch specified in $branch, for all subdirectories.
#
########################################################################################
#### [ Prepping ]


# Check if a branch name is provided as an argument.
if [[ -z $1 ]]; then
    echo "No branch specified. Usage: $0 <branch_name>"
    exit 1
fi


#### End of [ Prepping ]
########################################################################################
#### [ Variables ]


# The branch to checkout, provided by the first script argument.
branch="$1"
# The current directory.
current_dir=$(pwd)


#### End of [ Variables ]
########################################################################################
#### [ Main ]
#

for i in *; do
    [[ -d $i ]] || continue

    cd "$i" || {
        echo "Failed to change directory to '$i'..."
        echo "Skipping test..."
        continue
    }

    git checkout "$branch"
    rm -r ./*
    git restore \*

    cd "$current_dir" || {
        echo "Failed to change directory to '$current_dir'..."
        echo "Exiting to avoid data loss..."
        exit 1
    }
done


#### End of [ Main ]
########################################################################################

