#!/usr/bin/env bash
#
# .............................
#
########################################################################################


list=()

for i in "${list[@]}"; do
    repo="https://github.com/$i/EWU-CSCD371-2024-Winter.git"
    echo "Pulling $repo"
    git clone "$repo" "$i" || echo "Failed to pull $repo"
done

echo "Done"

