#!/usr/bin/env bash
#
# .............................
#
########################################################################################


for i in *; do
    [[ -d $i ]] || continue

    cd "$i" || {
        echo "Failed to change directory to '$i'..."
        echo "Skipping test..."
        continue
    }

    echo "Performing build and test for '$i'..."
    dotnet build
    dotnet test
    cd ../..
done
