#!/usr/bin/env bash
#
# .............................
#
########################################################################################


for i in *; do
    [[ -d $i ]] || continue

    cd "$i" || {
        echo "Failed to change directory to '$i'..."
        echo "Skipping test..."
        continue
    }

    echo "    $(git symbolic-ref --short HEAD)"
    cd ..
done
